[build]
  # Install at root, run the project build (which generates .netlify/functions-internal)
  # then explicitly install production deps into the generated function package so
  # Netlify's runtime can resolve runtime-only packages like @prisma/client.
  command = "pnpm install --frozen-lockfile --shamefully-hoist && pnpm run build && pnpm --prefix .netlify/functions-internal/server install --prod"
  publish = "dist"

[build.environment]
  FORCE_CACHE_BUST = "2"
  NODE_VERSION = "20"
  PACKAGE_MANAGER = "pnpm"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables for production
[context.production.environment]
  NITRO_PRESET = "netlify"
  NODE_ENV = "production"
  NODE_VERSION = "20"

[context.deploy-preview.environment]
  NITRO_PRESET = "netlify"
  NODE_ENV = "production"
  NODE_VERSION = "20"

[context.branch-deploy.environment]
  NITRO_PRESET = "netlify"
  NODE_ENV = "production"
  NODE_VERSION = "20"
