[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"

# For Nuxt 4 with Netlify preset
# Static assets go to 'dist', functions to '.netlify/functions-internal'

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables for production
[context.production.environment]
  NITRO_PRESET = "netlify"
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NITRO_PRESET = "netlify"
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NITRO_PRESET = "netlify"
  NODE_ENV = "production"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables for production
[context.production.environment]
  NITRO_PRESET = "netlify"
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NITRO_PRESET = "netlify"
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NITRO_PRESET = "netlify"
  NODE_ENV = "production"
